---
- name: My first playbook
  hosts: tags_Name_dcerino_ansible #is this our second instance? no it 1st
  gather_facts: true
  become: true
  vars_files:
    - "vars.yaml"

  roles:
    - bucket_create